charts/resoto/Chart.yaml, charts/resoto/README.md, charts/resoto/templates/resotometrics/deployment.yaml, charts/resoto/templates/resotometrics/service.yaml
This PR moves Prometheus annotations for `resotometrics` from the deployment to the service which is where default Prometheus looks for them (`kubernetes-service-endpoints` and `kubernetes-pods`). Also adds `https` scheme which is now default for all Resoto services.
=> [resotometrics][fix] move Prometheus annotations

.github/workflows/publish-chart.yaml, CNAME, README.md, index.html
Adds `README.md` with some basic information/links. Also adds a redirect from the root of the chart repository URL (https://helm.resoto.com) to redirect to this GitHub repository.
@aquamatthias Since this is the Some Engineering chart repository and not the Resoto chart repository, should we change the CNAME?
- Would need @lloesche to configure the subdomain `helm.some.engineering`. We'd want to set up a redirect from `helm.resoto.com` as well to keep existing setups working.
- Also would need to update the `README.md` in this PR as well as the Kubernetes install docs on resoto.com.
=> Add README to repo root

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [2.4.2](https://github.com/someengineering/resoto/releases/tag/2.4.2).
=> chore: bump appVersion to 2.4.2

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [2.4.4](https://github.com/someengineering/resoto/releases/tag/2.4.4).
=> chore: bump appVersion to 2.4.4

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [2.4.5](https://github.com/someengineering/resoto/releases/tag/2.4.5).
=> chore: bump appVersion to 2.4.5

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [2.4.7](https://github.com/someengineering/resoto/releases/tag/2.4.7).
=> chore: bump appVersion to 2.4.7

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.0.0](https://github.com/someengineering/resoto/releases/tag/3.0.0).
=> chore: bump appVersion to 3.0.0

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.0.2](https://github.com/someengineering/resoto/releases/tag/3.0.2).
=> chore: bump appVersion to 3.0.2

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.0.3](https://github.com/someengineering/resoto/releases/tag/3.0.3).
=> chore: bump appVersion to 3.0.3

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md, someengineering/resoto/templates/resotocore/ingress.yaml
using this example values.yaml
```
#...
resotocore:
ingress:
enabled: true
annotations:
kubernetes.io/ingress.class: kommander-traefik
hosts:
- paths:
- path: "/resoto"
pathType: ImplementationSpecific
```
we get an helm error message:
```
template: resoto/templates/resotocore/ingress.yaml:5:7: executing "resoto/templates/resotocore/ingress.yaml" at <include>: wrong number of args for include: want 2 got 1
```
this is due to `if include common.ingress.supportsIngressClassname` and `if include common.ingress.supportsPathType`: 
`common.ingress.supportsIngressClassname` and `common.ingress.supportsPathType` needs context as input see: https://artifacthub.io/packages/helm/bitnami/common#ingress
=> helm install fails with resotocore.ingress.enabled

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md, someengineering/resoto/templates/resotocore/deployment.yaml
`resotocore.extraEnv` was using a wrong indentation so whenever the variable was not empty an parsing error occurs
=> Fix - error when using resotocore.extraEnv

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md, someengineering/resoto/values.yaml
imagePullPolicy should not default to Always due to images being version. This avoids additional traffic and potential rate limiting on dockerhub
fix #63
=> fix: imagePullPolicy

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.2.0](https://github.com/someengineering/resoto/releases/tag/3.2.0).
=> chore: bump appVersion to 3.2.0

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.2.1](https://github.com/someengineering/resoto/releases/tag/3.2.1).
=> chore: bump appVersion to 3.2.1

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.2.2](https://github.com/someengineering/resoto/releases/tag/3.2.2).
=> chore: bump Resoto appVersion to 3.2.2

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.2.3](https://github.com/someengineering/resoto/releases/tag/3.2.3).
=> chore: bump Resoto appVersion to 3.2.3

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.2.4](https://github.com/someengineering/resoto/releases/tag/3.2.4).
=> chore: bump Resoto appVersion to 3.2.4

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.2.5](https://github.com/someengineering/resoto/releases/tag/3.2.5).
=> chore: bump Resoto appVersion to 3.2.5

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.3.0](https://github.com/someengineering/resoto/releases/tag/3.3.0).
=> chore: bump Resoto appVersion to 3.3.0

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.3.1](https://github.com/someengineering/resoto/releases/tag/3.3.1).
=> chore: bump Resoto appVersion to 3.3.1

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.3.2](https://github.com/someengineering/resoto/releases/tag/3.3.2).
=> chore: bump Resoto appVersion to 3.3.2

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.3.3](https://github.com/someengineering/resoto/releases/tag/3.3.3).
=> chore: bump Resoto appVersion to 3.3.3

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.4.1](https://github.com/someengineering/resoto/releases/tag/3.4.1).
=> chore: bump Resoto appVersion to 3.4.1

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.5.0](https://github.com/someengineering/resoto/releases/tag/3.5.0).
=> chore: bump Resoto appVersion to 3.5.0

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.5.1](https://github.com/someengineering/resoto/releases/tag/3.5.1).
=> chore: bump Resoto appVersion to 3.5.1

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.5.2](https://github.com/someengineering/resoto/releases/tag/3.5.2).
=> chore: bump Resoto appVersion to 3.5.2

.github/workflows/k8s-build.yaml, someengineering/resoto/Chart.yaml, someengineering/resoto/README.md, someengineering/resoto/templates/NOTES.txt, someengineering/resoto/templates/resotocore/ingress.yaml, someengineering/resoto/values.yaml
Fix: Ingress Template used the wrong scope and failed.
Chore: Bump dependencies to latest version
Feat: Add annotations for traefik and nginx to use https as backend communication
=> [fix] Ingress scope, bump libs and add annotations for nginx and traefik

someengineering/resoto/Chart.yaml, someengineering/resoto/README.md
Bumps Resoto version to [3.6.5](https://github.com/someengineering/resoto/releases/tag/3.6.5).
=> chore: bump Resoto appVersion to 3.6.5
